/* ══════════════════════════════════════════════════════════════════════════
   SHIVAA v167 — the accessibility repair layer (display-only, additive).

   WHY THIS EXISTS
   The site renders 140+ form fields whose visible <label> text was never
   associated with the field (no for=/id pair) — checkout address, contact,
   care, services, gift card, savings, buyback, B2B KYC and the whole admin
   panel. A screen reader announces those fields as "edit text, blank": the
   shopper is told what to type but not what it is. The markup is generated by
   dozens of separate template strings (and by admin.js, whose bytes are pinned
   by earlier releases), so instead of touching 140 call sites this one pass
   walks the rendered DOM and pairs each label with the control it already
   visually belongs to.

   HOW IT DECIDES
   · only inside a .fld block (the site's field wrapper), or the newsletter /
     pincode / coupon rows;
   · the control is either the label's next control sibling, the first control
     inside the next sibling container (calibrator, amount row, dropzone), or
     the only control in the block;
   · never touches a control that already has a name (aria-label, aria-labelledby,
     an enclosing <label>, or an existing for=);
   · gives the control a stable id only when it has none, then sets for=.

   Safe by construction: it adds attributes, never markup, never moves nodes,
   never invents text. Re-runs are no-ops. If it throws, the page is exactly what
   it was before (every step is inside try/catch).
   ══════════════════════════════════════════════════════════════════════════ */
'use strict';
(function () {
  if (window.__SHIVAA_A11Y167__) return;
  window.__SHIVAA_A11Y167__ = true;

  var SEQ = 0;
  var CTL = /^(INPUT|SELECT|TEXTAREA)$/;

  function text(el) { return (el.textContent || '').replace(/\s+/g, ' ').trim(); }

  function usable(el) {
    if (!el || el.disabled) return false;
    if (el.getAttribute('type') === 'hidden') return false;
    if (el.hasAttribute('hidden')) return false;          // e.g. the KYC card file input
    if (el.getAttribute('aria-hidden') === 'true') return false;
    if (el.getAttribute('aria-label') || el.getAttribute('aria-labelledby')) return false;
    if (el.closest && el.closest('label')) return false;  // already implied by its label
    return true;
  }

  function controlFor(label, block) {
    var n = label.nextElementSibling;
    while (n) {
      if (CTL.test(n.tagName)) return n;
      var inner = n.querySelector ? n.querySelector('input,select,textarea') : null;
      if (inner && CTL.test(inner.tagName)) return inner;
      n = n.nextElementSibling;
    }
    var all = block.querySelectorAll('input,select,textarea');
    return all.length === 1 ? all[0] : null;
  }

  function pair(label) {
    if (label.hasAttribute('for')) return;
    if (label.querySelector('input,select,textarea')) return;   // the label wraps its own field
    var block = label.closest('.fld, .fgroup, .pin-row, .coupon-row, .nl-form, .bbc-field, .kyc-drop');
    if (!block) return;
    var ctl = controlFor(label, block);
    if (!ctl || !usable(ctl)) return;
    if (!ctl.id) { do { SEQ++; } while (document.getElementById('shv-l167-' + SEQ)); ctl.id = 'shv-l167-' + SEQ; }
    label.setAttribute('for', ctl.id);
    try { nameExtraControls(label, block); } catch (e) {}
  }

  /* A block can hold TWO controls that belong to the same label — the savings
     plan and the gold buyback pair a number field with a slider. for= can name
     only one of them, so the second was left announced as a bare number. Any
     other control in a block whose label we just paired borrows the same name. */
  function nameExtraControls(label, block) {
    var txt = text(label).replace(/[*·:]+$/, '').trim();
    if (!txt || txt.length > 80) return;
    var named = label.getAttribute('for');
    var ctls = block.querySelectorAll('input,select,textarea');
    for (var i = 0; i < ctls.length; i++) {
      var c = ctls[i];
      if (c.id && named === c.id) continue;      // this IS the paired control
      if (!usable(c)) continue;
      c.setAttribute('aria-label', txt);
    }
  }

  /* Fields with a name but no label at all in their block (the calibrator rows,
     the savings amount row): give the control the nearest short text above it. */
  function nameStrayControls(scope) {
    var ctl = scope.querySelectorAll('input:not([type=hidden]),select,textarea');
    for (var i = 0; i < ctl.length; i++) {
      var el = ctl[i];
      if (!usable(el)) continue;
      if (el.hasAttribute('placeholder')) continue;          // browsers/AT read the placeholder
      var host = el.closest('.fld, .fgroup, .bbc-field, .pin-row, .coupon-row, .svc-amt-row, .bbc-wt');
      if (!host) continue;
      var lb = host.querySelector('label');
      if (lb) continue;                                      // handled by pair()
      var prev = host.previousElementSibling;
      var t = prev ? text(prev) : '';
      if (!t || t.length > 60) { var b = host.querySelector('b, .lbl, .fld-h'); t = b ? text(b) : ''; }
      if (t && t.length <= 60) el.setAttribute('aria-label', t);
    }
  }

  function sweep(root) {
    try {
      var scope = root && root.querySelectorAll ? root : document;
      var labels = scope.querySelectorAll('label');
      for (var i = 0; i < labels.length; i++) { try { pair(labels[i]); } catch (e) {} }
      try { nameStrayControls(scope); } catch (e) {}
    } catch (e) {}
  }

  var queued = false;
  function queue() {
    if (queued) return; queued = true;
    setTimeout(function () { queued = false; sweep(document); }, 120);
  }

  function boot() {
    sweep(document);
    try {
      if (typeof MutationObserver === 'function' && document.body) {
        new MutationObserver(queue).observe(document.body, { childList: true, subtree: true });
      }
    } catch (e) {}
  }
  /* window.Shivaa exposes 167 as the release layer · keep the same door the
     other layers use for a manual re-run after a big paint. */
  try { (window.Shivaa = window.Shivaa || {}).a11yFix = function () { sweep(document); }; } catch (e) {}

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
